- name: install uzip
  apt:
   name: unzip

- name: Install AWS CLI
  shell: >
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
    unzip awscliv2.zip &&
    ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
- name: Create .aws directory
  file:
    path: /home/ubuntu/.aws
    state: directory

- name: Create credentials file with AWS access keys
  copy:
    content: |
      [default]
      aws_access_key_id = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}
    dest: "/home/ubuntu/.aws/credentials"
